-- Task 1: Retrieve customer information along with the total number of orders
SELECT
    c.customer_id,
    c.name,
    c.email,
    c.location,
    COUNT(o.order_id) AS total_orders
FROM Customers c
LEFT JOIN Orders o ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.name, c.email, c.location
ORDER BY total_orders DESC;


-- Task 2: Retrieve product name, quantity, and total amount for each order item
SELECT
    p.name AS product_name,
    oi.quantity,
    (oi.quantity * oi.unit_price) AS total_amount
FROM Order_Items oi
JOIN Products p ON oi.product_id = p.product_id
ORDER BY oi.order_id ASC;

-- Task 3: Retrieve the total revenue generated by each product category
SELECT
    c.name AS category_name,
    SUM(oi.quantity * oi.unit_price) AS total_revenue
FROM Order_Items oi
JOIN Products p ON oi.product_id = p.product_id
JOIN Categories c ON p.category_id = c.category_id
GROUP BY c.name
ORDER BY total_revenue DESC;

-- Task 4: Retrieve the top 5 customers with the highest total purchase amount
SELECT
    c.name AS customer_name,
    SUM(oi.quantity * oi.unit_price) AS total_purchase_amount
FROM Customers c
JOIN Orders o ON c.customer_id = o.customer_id
JOIN Order_Items oi ON o.order_id = oi.order_id
GROUP BY c.name
ORDER BY total_purchase_amount DESC
LIMIT 5;
